/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uok.oop.calculator;

/**
 *
 * @author thish
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    
    double num, ans;
    int calculation;
    
    public Calculator() {
        initComponents();
    }

    public void arithmeticOperation()
    {
        switch(calculation)
        {
            case 1://Addition
                ans = num + Double.parseDouble(jTextField.getText());
                jTextField.setText(Double.toString(ans));
                break;
                
            case 2://Subtraction
                ans = num - Double.parseDouble(jTextField.getText());
                jTextField.setText(Double.toString(ans));
                break;
                
            case 3://Multiplication
                ans = num * Double.parseDouble(jTextField.getText());
                jTextField.setText(Double.toString(ans));
                break;
                
            case 4://Division
                ans = num / Double.parseDouble(jTextField.getText());
                jTextField.setText(Double.toString(ans));
                break;
                
            case 5://Percentage
                ans = num / 100;
                jTextField.setText(Double.toString(ans));
                break;
                
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField = new javax.swing.JTextField();
        jButtonDivision = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jButtonMultiple = new javax.swing.JButton();
        jButtonBackSpace = new javax.swing.JButton();
        jButtonDigit8 = new javax.swing.JButton();
        jButtonDigit7 = new javax.swing.JButton();
        jButtonDigit9 = new javax.swing.JButton();
        jButtonPlusOrMinus = new javax.swing.JButton();
        jButtonDigit5 = new javax.swing.JButton();
        jButtonDigit4 = new javax.swing.JButton();
        jButtonDigit6 = new javax.swing.JButton();
        jButtonSubtraction = new javax.swing.JButton();
        jButtonDigit2 = new javax.swing.JButton();
        jButtonDigit1 = new javax.swing.JButton();
        jButtonDigit3 = new javax.swing.JButton();
        jButtonAddition = new javax.swing.JButton();
        jButtonDigit0 = new javax.swing.JButton();
        jButtonPercentage = new javax.swing.JButton();
        jButtonDot = new javax.swing.JButton();
        jButtonEqual = new javax.swing.JButton();
        jLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");

        jTextField.setFont(new java.awt.Font("Tw Cen MT", 0, 48)); // NOI18N
        jTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldActionPerformed(evt);
            }
        });

        jButtonDivision.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButtonDivision.setText("÷");
        jButtonDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivisionActionPerformed(evt);
            }
        });

        jButtonClear.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jButtonClear.setText("C");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButtonMultiple.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButtonMultiple.setText("×");
        jButtonMultiple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultipleActionPerformed(evt);
            }
        });

        jButtonBackSpace.setFont(new java.awt.Font("Segoe UI Symbol", 1, 36)); // NOI18N
        jButtonBackSpace.setText("");
        jButtonBackSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackSpaceActionPerformed(evt);
            }
        });

        jButtonDigit8.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jButtonDigit8.setText("8");
        jButtonDigit8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDigit8ActionPerformed(evt);
            }
        });

        jButtonDigit7.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jButtonDigit7.setText("7");
        jButtonDigit7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDigit7ActionPerformed(evt);
            }
        });

        jButtonDigit9.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jButtonDigit9.setText("9");
        jButtonDigit9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDigit9ActionPerformed(evt);
            }
        });

        jButtonPlusOrMinus.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButtonPlusOrMinus.setText("±");
        jButtonPlusOrMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlusOrMinusActionPerformed(evt);
            }
        });

        jButtonDigit5.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jButtonDigit5.setText("5");
        jButtonDigit5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDigit5ActionPerformed(evt);
            }
        });

        jButtonDigit4.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jButtonDigit4.setText("4");
        jButtonDigit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDigit4ActionPerformed(evt);
            }
        });

        jButtonDigit6.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jButtonDigit6.setText("6");
        jButtonDigit6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDigit6ActionPerformed(evt);
            }
        });

        jButtonSubtraction.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButtonSubtraction.setText("−");
        jButtonSubtraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubtractionActionPerformed(evt);
            }
        });

        jButtonDigit2.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jButtonDigit2.setText("2");
        jButtonDigit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDigit2ActionPerformed(evt);
            }
        });

        jButtonDigit1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jButtonDigit1.setText("1");
        jButtonDigit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDigit1ActionPerformed(evt);
            }
        });

        jButtonDigit3.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jButtonDigit3.setText("3");
        jButtonDigit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDigit3ActionPerformed(evt);
            }
        });

        jButtonAddition.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButtonAddition.setText("+");
        jButtonAddition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdditionActionPerformed(evt);
            }
        });

        jButtonDigit0.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jButtonDigit0.setText("0");
        jButtonDigit0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDigit0ActionPerformed(evt);
            }
        });

        jButtonPercentage.setFont(new java.awt.Font("Cambria Math", 1, 36)); // NOI18N
        jButtonPercentage.setText("%");
        jButtonPercentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPercentageActionPerformed(evt);
            }
        });

        jButtonDot.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jButtonDot.setText(".");
        jButtonDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDotActionPerformed(evt);
            }
        });

        jButtonEqual.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButtonEqual.setText("=");
        jButtonEqual.setToolTipText("");
        jButtonEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEqualActionPerformed(evt);
            }
        });

        jLabel.setForeground(new java.awt.Color(255, 0, 0));
        jLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDigit7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDigit4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDigit1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDigit8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDigit5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDigit2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDigit0, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonMultiple, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDigit9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDigit6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDigit3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonBackSpace, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(jButtonPlusOrMinus, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(jButtonSubtraction, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(jButtonAddition, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(jButtonEqual, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDigit7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDigit4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDigit1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDigit8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDigit5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonDigit2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDigit3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDigit0, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonBackSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonDigit9, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonDigit6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAddition, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonPlusOrMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSubtraction, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonDot, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(jButtonEqual, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivisionActionPerformed
        num = Double.parseDouble(jTextField.getText());
        calculation = 4;
        jTextField.setText("");
        jLabel.setText(num + "÷"); 
    }//GEN-LAST:event_jButtonDivisionActionPerformed

    private void jButtonMultipleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultipleActionPerformed
        num = Double.parseDouble(jTextField.getText());
        calculation = 3;
        jTextField.setText("");
        jLabel.setText(num + "×"); 
    }//GEN-LAST:event_jButtonMultipleActionPerformed

    private void jButtonBackSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackSpaceActionPerformed
        int length = jTextField.getText().length();
        int number = jTextField.getText().length() - 1;
        String store;
        
        if (length > 0)
        {
            StringBuilder back = new StringBuilder(jTextField.getText());
            back.deleteCharAt(number);
            store = back.toString();
            jTextField.setText(store);
        }
    }//GEN-LAST:event_jButtonBackSpaceActionPerformed

    private void jButtonDigit8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDigit8ActionPerformed
        jTextField.setText(jTextField.getText() + "8");
    }//GEN-LAST:event_jButtonDigit8ActionPerformed

    private void jButtonDigit9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDigit9ActionPerformed
        jTextField.setText(jTextField.getText() + "9");
    }//GEN-LAST:event_jButtonDigit9ActionPerformed

    private void jButtonPlusOrMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlusOrMinusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPlusOrMinusActionPerformed

    private void jButtonDigit5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDigit5ActionPerformed
        jTextField.setText(jTextField.getText() + "5");
    }//GEN-LAST:event_jButtonDigit5ActionPerformed

    private void jButtonDigit6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDigit6ActionPerformed
        jTextField.setText(jTextField.getText() + "6");
    }//GEN-LAST:event_jButtonDigit6ActionPerformed

    private void jButtonSubtractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubtractionActionPerformed
        num = Double.parseDouble(jTextField.getText());
        calculation = 2;
        jTextField.setText("");
        jLabel.setText(num + "-"); 
    }//GEN-LAST:event_jButtonSubtractionActionPerformed

    private void jButtonDigit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDigit2ActionPerformed
        jTextField.setText(jTextField.getText() + "2");
    }//GEN-LAST:event_jButtonDigit2ActionPerformed

    private void jButtonDigit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDigit3ActionPerformed
        jTextField.setText(jTextField.getText() + "3");
    }//GEN-LAST:event_jButtonDigit3ActionPerformed

    private void jButtonAdditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdditionActionPerformed
        num = Double.parseDouble(jTextField.getText());
        calculation = 1;
        jTextField.setText("");
        jLabel.setText(num + "+");
    }//GEN-LAST:event_jButtonAdditionActionPerformed

    private void jButtonDigit0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDigit0ActionPerformed
        jTextField.setText(jTextField.getText() + "0");
    }//GEN-LAST:event_jButtonDigit0ActionPerformed

    private void jButtonDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDotActionPerformed
        jTextField.setText(jTextField.getText() + ".");
    }//GEN-LAST:event_jButtonDotActionPerformed

    private void jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        jTextField.setText("");
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonDigit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDigit1ActionPerformed
        jTextField.setText(jTextField.getText() + "1");
    }//GEN-LAST:event_jButtonDigit1ActionPerformed

    private void jButtonDigit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDigit4ActionPerformed
        jTextField.setText(jTextField.getText() + "4");
    }//GEN-LAST:event_jButtonDigit4ActionPerformed

    private void jButtonDigit7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDigit7ActionPerformed
        jTextField.setText(jTextField.getText() + "7");
    }//GEN-LAST:event_jButtonDigit7ActionPerformed

    private void jButtonPercentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPercentageActionPerformed
        num = Double.parseDouble(jTextField.getText());
        calculation = 5;
        jTextField.setText("");
        jLabel.setText(num + "%");
    }//GEN-LAST:event_jButtonPercentageActionPerformed

    private void jButtonEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEqualActionPerformed
        arithmeticOperation();
        jLabel.setText("");
    }//GEN-LAST:event_jButtonEqualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddition;
    private javax.swing.JButton jButtonBackSpace;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDigit0;
    private javax.swing.JButton jButtonDigit1;
    private javax.swing.JButton jButtonDigit2;
    private javax.swing.JButton jButtonDigit3;
    private javax.swing.JButton jButtonDigit4;
    private javax.swing.JButton jButtonDigit5;
    private javax.swing.JButton jButtonDigit6;
    private javax.swing.JButton jButtonDigit7;
    private javax.swing.JButton jButtonDigit8;
    private javax.swing.JButton jButtonDigit9;
    private javax.swing.JButton jButtonDivision;
    private javax.swing.JButton jButtonDot;
    private javax.swing.JButton jButtonEqual;
    private javax.swing.JButton jButtonMultiple;
    private javax.swing.JButton jButtonPercentage;
    private javax.swing.JButton jButtonPlusOrMinus;
    private javax.swing.JButton jButtonSubtraction;
    private javax.swing.JLabel jLabel;
    private javax.swing.JTextField jTextField;
    // End of variables declaration//GEN-END:variables
}
